name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: drivncook_test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports: [ "33306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer:v2 }
      - name: Install deps
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=mysql/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=drivncook/DB_DATABASE=drivncook_test/' .env
          sed -i 's/DB_USERNAME=sail/DB_USERNAME=user/' .env
          sed -i 's/DB_PASSWORD=password/DB_PASSWORD=pass/' .env
          composer install --no-interaction --prefer-dist
          php artisan key:generate
      - name: Migrate
        run: php artisan migrate --force
      - name: Pint
        run: vendor/bin/pint --test
      - name: PHPUnit/Pest
        run: php artisan test --colors=always
